Repository hmcts/ia-home-office-mock-api, pull requests merged in 2020-07, with the labels that each got.

#22 RIA-3381:Update mock server with API spec
  build.gradle
Labels: ns:ia, prd:ia, rel:ia-home-office-mock-api-pr-22

#24 RIA-3271:Change mock response for HO API Validation
  src/main/java/uk/gov/hmcts/reform/iahomeofficemockapi/generated/infrastructure/api/ApplicationStatusApi.java
Labels: ns:ia, prd:ia, rel:ia-home-office-mock-api-pr-24

#23 RIA-3447 upgrading to java11
  .travis.yml
  Dockerfile
  build.gradle
Labels: ns:ia, prd:ia, rel:ia-home-office-mock-api-pr-23
